### ISSUE TITLE
Can you recommend a code generator?

### ISSUE THREAD

**Issue by shulandmimi** [g-plane/raffia#4]
`css/scss/less` ast -> `css/scss/less` code

**Comment by g-plane** [comment]
Can you provide more detail? I can't understand your question.

**Comment by shulandmimi** [comment]
I wrote a tool based on Raffia using rust, but I didn't find a suitable library to convert AST to code

**Comment by g-plane** [comment]
It's just a parser. Currently I have no plans about code generating.

**Comment by shulandmimi** [comment]
maybe i can try
